# Generated by Django 4.2.29 on 2026-03-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_transfer_transferitem_stockbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
