# Generated by Django 4.2.29 on 2026-03-23 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_goodsreceiptitem_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptitem',
            name='created_at',
        ),
    ]
